### ISSUE TITLE
promscale secret is missing

### ISSUE THREAD

**Issue by e9169** [timescale/opentelemetry-demo#17]
While deploying in kubernetes, check service cannot be initialized since it throws a CreateContainerConfigError since secret "tobs-promscale" is missing.

I just followed the instructions to kubectl apply the yaml files in the yaml folder.

**Comment by e9169** [comment]
Since I can not push to the repo and create a branch and PR, I will leave here the changes I made to make it work:

secret.yaml in yaml/app/check/

```
apiVersion: v1
kind: Secret
metadata:
  name: tobs-promscale
type: Opaque
data:
  PROMSCALE_DB_USER: cG9zdGdyZXMK
  PROMSCALE_DB_PASSWORD: cGFzc3dvcmQK
  PROMSCALE_DB_HOST: dGltZXNjYWxlZGIK
  PROMSCALE_DB_NAME: b3RlbF9kZW1vCg==
```
Append secret.yaml to kustomize.yaml

This data is based on the docker-compose file.
